# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:

jobs:
  build:
    name: PrimeiroJob
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      - name: Executando o STEP1
        run: |
          echo "Esse processo carrega uma mensagem"
          echo "básica para entender o workflow"

